name: CI workflow

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Continuous integration with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml